TY-2726 key phrase selection tests
xaynetwork/xayn_discovery_engine pull request #321
Opened 2022-04-14 14:47 UTC by janpetschexain

**References**

- [TY-2726]
- #299, #302

**Summary**

- simplify test setup
- make `reduce_without_diag()` more robust in edge cases
- simplify `reduce_without_diag()` and `argmax()` function signatures
- generalize `is_selected()` and `select()` function signatures
- add tests for the remaining uncovered key phrase selection subfunctionality

2022-04-19 13:18 UTC, rustonaut requested changes
Mostly lgtm, but I found one thing in the tested code which probably should be changed and get an additional test.

Also two other minor things which don't need to be changed, but it probably would be better to do so.

2022-04-19 13:18 UTC, rustonaut commented on discovery_engine_core/ai/xayn-ai/src/coi/key_phrase.rs
> +
:wrench:? This test depends on the default config values, maybe we should assert them to be equal to the values we expect to have easier to understand failures when we change the default values;

2022-04-19 13:40 UTC, janpetschexain commented on discovery_engine_core/ai/xayn-ai/src/coi/key_phrase.rs
>                  .map(|reduced| finalize(reduced, i < lane.len()))
this is what i wanted to say as well, i'll try to find a better phrasing of the documentation.

2022-04-20 11:00 UTC, rustonaut approved these changes
lgtm

2022-04-20 11:30 UTC, janpetschexain commented
bors merge

2022-04-20 11:46 UTC, closed without merging